name: ipylab-lite
channels:
- conda-forge
dependencies:
- python-build
- python=3.11
- pip
- mamba
- pydata-sphinx-theme
- myst-parser
- ipywidgets >=8.0,<9
- jupyterlab >=4,<5
- jupyterlite-core >=0.1.1,<0.2.0
- jupyterlite-pyodide-kernel >=0.1.0,<0.2.0
- jupyterlite-sphinx >=0.9.1,<0.10.0
- nodejs=18
- pip:
  - ..
